### PR TITLE
Fix bug in generating random numbers for sphere

### PR DESCRIPTION
**Pull request by jzuhone**
In the updates which enabled Python 3 compatibility (PR #9), a call to `numpy.random.random` was changed to `prng.uniform`, both of which generate uniformly distributed random numbers, but have slightly different signatures. 

If one calls `numpy.random.random` with a single argument, that argument is the number of elements in the array which is returned. However, if one calls `prng.uniform` with a single argument, that number is not the size of the array which results. This one-line PR fixes it.

### CODE REVIEW

**Comment by jzuhone** [comment]
Ping @taldcroft @jeanconn

**Comment by jzuhone** [comment]
Some plots showing the improvement in the agreement between the "old" version of taco, the "new" version currently in SOT flight Ska3, and the "fixed" version represented in this pull request. There are still some differences, because the random numbers being generated are not the same, but these are expected and acceptable within known errors in the thermal models.

"old" taco vs. "new" taco temperatures:

old_vs_new_temp

"old" taco vs. "fixed" taco temperatures:

old_vs_fixed_temp

temperature differences:

diff_temp

"old" taco vs. "new" taco earth solid angle:

old_vs_new_esa

"old" taco vs. "fixed" taco earth solid angle:

old_vs_fixed_esa

earth solid angle differences:

diff_esa

**Comment by jzuhone** [comment]
@taldcroft @jeanconn I added a regression test.

**Comment by taldcroft** [comment]
@jzuhone - can you state for the record the package versions and Ska configuration you used for "old" and for "new", respectively?  I assume "fixed" is with this PR locally and Ska3-flight.

For the new regression test, can you confirm that it fails for "new"?

Since the new `illum.npy` file only contains 11 numbers, it might be just as easy to hardwire those values into the test module.  It's just a bit simpler and more transparent in the case of later regressions since the diffs can be seen in github.  Also, I believe that currently the new `illum.npy` is not included in the package data so the test would fail after installation.  (Well.. setuptools is always baffling to me so not 100% on that).

**Comment by jeanconn** [comment]
Also, when I try to run the new test I just get "E           FileNotFoundError: [Errno 2] No such file or directory: 'illum.npy'".  I see that there is a new illum.npy file in the repo and I haven't tried to figure out if is in the wrong place or...

**Comment by jzuhone** [comment]
@jeanconn I think @taldcroft's suggestion of just hard-coding the numbers in the Python file is better and would avoid that issue.

**Comment by jzuhone** [comment]
@taldcroft I used:

"old" --> flight ska2 with Chandra.taco v0.2.1 (git commit 002e69e1b18ce80fe58b1e066ceccfd027f5a2b0)
"new" --> flight ska3 with acis_taco v4.0 (git commit b013ba25de96979587d26c7811fa1f73d3ff65ee)
"fixed" --> flight ska3 with this PR

**Comment by jeanconn** [comment]
Quick question, do we have any reason to want to install this on Ska2 or are we good with just Ska3 moving forward here?

**Comment by jeanconn** [comment]
Oh and I can't remember my semantic versioning rules to recall what a back-compatible bug fix *is* to know if this should be 4.1 or 4.0.1 (I see John has gone with 4.0.1).

**Comment by jzuhone** [comment]
I can now verify that the test fails for the master branch.

**Comment by taldcroft** [comment]
@jeanconn - once John does the squash, can you take care of the rest? 

About Ska2, if we don't install to Ska2 then we need to formally declare Ska2 *not* approved for ACIS load review since it has a known bug.  As a practical matter that is the case.

**Comment by jzuhone** [comment]
file is gone.

**Comment by jeanconn** [comment]
Regarding "About Ska2, if we don't install to Ska2 then we need to formally declare Ska2 not approved for ACIS load review since it has a known bug. As a practical matter that is the case."  That was my thought as well.  I also thought we could perhaps install this in Ska2 but noticed the tests (up to and including the new one) didn't seem to pass so it didn't seem worth the work.

**Comment by jeanconn** [comment]
For Ska2 an alternative path might be to uninstall acis_taco (but not seeing much point?).

**Comment by swolk** [comment]
Thanks John, this looks MUCH better,  I assume the remaining discrepancies are only due to timing.

**Pull request merged**
